{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user gagan.aws.ac@gmail.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-10T14:38:02.620Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user gagan.aws.ac@gmail.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-11T04:56:35.260Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user gagan.io.@asn.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-11T07:09:05.667Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user gagan.aws.ac@gmail.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-11T09:13:39.607Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user gagan.io.@asn.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-11T09:22:16.610Z"}
{"code":"42601","file":"scan.l","length":99,"level":"error","line":"1188","message":"Postgres QUERY error:\n    INSERT INTO users(firstname, lastname, email, password, auth_type, profile_picture created_at)\n    VALUES($1, $2, $3, $4, $5, $6 CURRENT_TIMESTAMP) RETURNING id syntax error at or near \"created_at\"","name":"error","position":"89","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Code\\ExpenseTrackerApp\\server\\expenseTracker-auth-service\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async pgQuery (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/dbconnection.js:19:24)\n    at async insertUser (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/model/userModel.js:22:18)\n    at async registerUserService (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/services/authService.js:20:16)","timestamp":"2025-09-12T03:26:57.924Z"}
{"code":"42601","file":"scan.l","length":99,"level":"error","line":"1188","message":"Postgres QUERY error:\n    INSERT INTO users(firstname, lastname, email, password, auth_type, profile_picture created_at)\n    VALUES($1, $2, $3, $4, $5, $6 CURRENT_TIMESTAMP) RETURNING id syntax error at or near \"created_at\"","name":"error","position":"89","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Code\\ExpenseTrackerApp\\server\\expenseTracker-auth-service\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async pgQuery (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/dbconnection.js:19:24)\n    at async insertUser (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/model/userModel.js:22:18)\n    at async registerUserService (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/services/authService.js:20:16)","timestamp":"2025-09-12T04:15:49.522Z"}
{"code":"42601","file":"scan.l","length":99,"level":"error","line":"1188","message":"Postgres QUERY error:\n    INSERT INTO users(firstname, lastname, email, password, auth_type, profile_picture created_at)\n    VALUES($1, $2, $3, $4, $5, $6 CURRENT_TIMESTAMP) RETURNING id syntax error at or near \"created_at\"","name":"error","position":"89","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Code\\ExpenseTrackerApp\\server\\expenseTracker-auth-service\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async pgQuery (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/dbconnection.js:19:24)\n    at async insertUser (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/model/userModel.js:22:18)\n    at async registerUserService (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/services/authService.js:21:18)","timestamp":"2025-09-12T04:24:22.137Z"}
{"code":"42601","file":"scan.l","length":99,"level":"error","line":"1188","message":"Postgres QUERY error:\n    INSERT INTO users(firstname, lastname, email, password, auth_type, profile_picture created_at)\n    VALUES($1, $2, $3, $4, $5, $6 CURRENT_TIMESTAMP) RETURNING id syntax error at or near \"created_at\"","name":"error","position":"89","routine":"scanner_yyerror","severity":"ERROR","stack":"error: syntax error at or near \"created_at\"\n    at C:\\Code\\ExpenseTrackerApp\\server\\expenseTracker-auth-service\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async pgQuery (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/dbconnection.js:19:24)\n    at async insertUser (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/model/userModel.js:23:18)\n    at async registerUserService (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/services/authService.js:21:18)","timestamp":"2025-09-12T04:26:46.181Z"}
{"cause":{},"level":"error","message":"Postgres QUERY error:SELECT * FROM users WHERE EMAIL=$1 Connection terminated due to connection timeout","stack":"Error: Connection terminated due to connection timeout\n    at C:\\Code\\ExpenseTrackerApp\\server\\expenseTracker-auth-service\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async pgQuery (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/dbconnection.js:19:24)\n    at async findUserByEmail (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/model/userModel.js:4:18)\n    at async loginUserService (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/services/authService.js:89:29)","timestamp":"2025-09-12T06:19:47.720Z"}
{"cause":{},"level":"error","message":"Error caught at Login Step:\n Connection terminated due to connection timeout","stack":"Error: Connection terminated due to connection timeout\n    at C:\\Code\\ExpenseTrackerApp\\server\\expenseTracker-auth-service\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async pgQuery (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/dbconnection.js:19:24)\n    at async findUserByEmail (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/model/userModel.js:4:18)\n    at async loginUserService (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/src/services/authService.js:89:29)","timestamp":"2025-09-12T06:19:47.722Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user abcd@asn.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-12T07:02:03.641Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user 1231212@asn.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-12T07:31:08.906Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user abcd@asn.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-13T07:27:04.729Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user ssdfsdfsdfsdfsdf@qwe1231.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-13T12:01:10.393Z"}
{"code":"ESOCKET","command":"CONN","level":"error","message":"Error in sending OTP mail to user gagan.aws.a1c@gmail.com unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:520:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","timestamp":"2025-09-23T08:02:32.158Z"}
{"level":"error","message":"Error connecting postgres: result.rows[0].now is not a function","stack":"TypeError: result.rows[0].now is not a function\n    at pgConnectTest (file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/config/dbconnection.js:32:71)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///C:/Code/ExpenseTrackerApp/server/expenseTracker-auth-service/utils/healthcheckUp.js:18:13","timestamp":"2025-09-23T09:03:52.123Z"}
